CREATE TABLE TB_CLIENTE 
( 
 ID_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,  
 CLI_NOME CHAR(n) NOT NULL,  
 CLI_SOBRENOME CHAR(n) NOT NULL,  
 CLI_CPF INT NOT NULL,  
 CLI_DTNASC DATE NOT NULL,  
 CLI_SEXO CHAR(n) NOT NULL,  
 CLI_ESTADOCIVIL CHAR(n) NOT NULL,  
 CLI_EMAIL VARCHAR(n) NOT NULL,  
 CLI_TELEFONE1 VARCHAR(n) NOT NULL,  
 CLI_TELEFONE2 VARCHAR(n),  
 CLI_CEP INT NOT NULL,  
 CLI_PAIS CHAR(n) NOT NULL,  
 CLI_UF CHAR(n) NOT NULL,  
 CLI_CIDADE VARCHAR(n) NOT NULL,  
 CLI_RUA VARCHAR(n) NOT NULL,  
 CLI_NUMERO INT NOT NULL,  
 CLI_DTCAD DATE NOT NULL AUTO_INCREMENT,  
 CLI_STATUS INT NOT NULL DEFAULT '1',  
 CLI_FOTO VARCHAR(n),  
 UNIQUE (CLI_CPF,CLI_EMAIL)
); 

CREATE TABLE TB_LOGIN 
( 
 ID_LOGIN INT PRIMARY KEY AUTO_INCREMENT,  
 CLI_EMAIL INT NOT NULL,  
 CLI_SENHA INT NOT NULL,  
 ADM_EMAIL VARCHAR(n),  
 ADM_SENHA VARCHAR(n) NOT NULL,  
 ADM_NOME CHAR(n) NOT NULL,  
 CLI_NOME CHAR(n) NOT NULL,  
 UNIQUE (CLI_EMAIL: FK)
); 

CREATE TABLE TB_FEEDBACK 
( 
 ID_FEEDBACK INT PRIMARY KEY AUTO_INCREMENT,  
 ID_CLIENTE INT NOT NULL,  
 CLI_NOME CHAR(n) NOT NULL,  
 CLI_FOTO VARCHAR(n),  
 CLI_EMAIL VARCHAR(n) NOT NULL,  
 CLI_PAIS CHAR(n) NOT NULL,  
 FED_DESCRICAO VARCHAR(n) NOT NULL,  
 FED_NOTA FLOAT NOT NULL,  
 FED_DTFEEDBACK DATE NOT NULL AUTO_INCREMENT,  
 PRO_BARCODE INT,  
); 

CREATE TABLE TB_ADMIN 
( 
 ID_ADMIN INT PRIMARY KEY AUTO_INCREMENT,  
 ADM_NOME CHAR(n) NOT NULL,  
 ADM_SOBRENOME CHAR(n) NOT NULL,  
 ADM_EMAIL VARCHAR(n) NOT NULL,  
 ADM_CARGO VARCHAR(n) NOT NULL,  
 ADM_FOTO VARCHAR(n),  
); 

CREATE TABLE TB_PRODUTO 
( 
 PRO_BARCODE INT PRIMARY KEY,  
 ID_ESTOQUE INT,  
 PRO_NOME VARCHAR(n) NOT NULL,  
 PRO_DESCRICAO VARCHAR(n) NOT NULL,  
 PRO_PRECO FLOAT NOT NULL,  
 PRO_CATEGORIA VARCHAR(n) NOT NULL,  
 PRO_TAMANHO VARCHAR(n) NOT NULL,  
 PRO_COR CHAR(n) NOT NULL,  
 PRO_MATERIAL CHAR(n) NOT NULL,  
 PRO_IMAGEM VARCHAR(n) NOT NULL,  
 ADM_EMAIL VARCHAR(n),  
); 

CREATE TABLE TB_ESTOQUE 
( 
 ID_ESTOQUE INT PRIMARY KEY,  
 FOR_CNPJ INT,  
 PRO_BARCODE INT,  
 EST_CEP INT NOT NULL,  
 EST_NUMERO INT NOT NULL,  
 EST_QUANTIDADE INT NOT NULL,  
); 

CREATE TABLE TB_FORNECEDOR 
( 
 FOR_CNPJ INT PRIMARY KEY,  
 FOR_NOME VARCHAR(n),  
 FOR_RAZAOSOCIAL VARCHAR(n) NOT NULL,  
 FOR_PAIS CHAR(n) NOT NULL,  
 FOR_UF CHAR(n) NOT NULL,  
 FOR_CIDADE VARCHAR(n) NOT NULL,  
 FOR_RUA VARCHAR(n) NOT NULL,  
 FOR_NUMERO INT NOT NULL,  
 FOR_CEP INT NOT NULL,  
); 

CREATE TABLE TB_PEDIDO 
( 
 ID_PEDIDO INT PRIMARY KEY,  
 PRO_BARCODE INT,  
 ID_CLIENTE INT,  
 PED_QUANTIDADE INT NOT NULL,  
 PED_PAGAMENTO FLOAT NOT NULL,  
 PED_DTPEDIDO DATE NOT NULL AUTO_INCREMENT,  
); 

ALTER TABLE TB_LOGIN ADD FOREIGN KEY(CLI_EMAIL) REFERENCES TB_CLIENTE (CLI_EMAIL)
ALTER TABLE TB_LOGIN ADD FOREIGN KEY(ADM_EMAIL) REFERENCES TB_ADMIN (ADM_EMAIL)
ALTER TABLE TB_FEEDBACK ADD FOREIGN KEY(ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE)
ALTER TABLE TB_FEEDBACK ADD FOREIGN KEY(PRO_BARCODE) REFERENCES TB_PRODUTO (PRO_BARCODE)
ALTER TABLE TB_PRODUTO ADD FOREIGN KEY(ID_ESTOQUE) REFERENCES TB_ESTOQUE (ID_ESTOQUE)
ALTER TABLE TB_PRODUTO ADD FOREIGN KEY(ADM_EMAIL) REFERENCES TB_ADMIN (ADM_EMAIL)
ALTER TABLE TB_ESTOQUE ADD FOREIGN KEY(FOR_CNPJ) REFERENCES TB_FORNECEDOR (FOR_CNPJ)
ALTER TABLE TB_ESTOQUE ADD FOREIGN KEY(PRO_BARCODE) REFERENCES TB_PRODUTO (PRO_BARCODE)
ALTER TABLE TB_PEDIDO ADD FOREIGN KEY(PRO_BARCODE) REFERENCES TB_PRODUTO (PRO_BARCODE)
ALTER TABLE TB_PEDIDO ADD FOREIGN KEY(ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE)
